name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ghc: ["9.8", "9.6"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ matrix.ghc }}-
            ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --only-dependencies

      - name: Build and Test
        run: stack test
